### ISSUE TITLE
Won't work with Python 3.6.x

### ISSUE THREAD

**Issue by brianlie-tokopedia** [maztohir/bigquery-sql-parser#7]
Reproducing with these steps

- Create a conda environment `conda create -n sqlparser python=3.6`
- Activate conda environment `conda activate sqlparser`
- Install using pip via python binary `python -m pip install bigquery-sql-parser`
- Open a Python interpreter and try to import the package

```
>>> from bigquery_sql_parser import query
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brian.lie/miniconda3/envs/parser/lib/python3.6/site-packages/bigquery_sql_parser/query.py", line 8, in <module>
    from .tokenizer import Tokenizer
  File "/Users/brian.lie/miniconda3/envs/parser/lib/python3.6/site-packages/bigquery_sql_parser/tokenizer.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by maztohir** [comment]
Hi @brianlie-tokopedia , 
I will check on it, but as of now, would you mind using python=3.8 as a temp solution?

Thanks for noticing on this.
